CREATE TABLE IF NOT EXISTS `%PREFIX%activity_history` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` BIGINT(20) NULL DEFAULT NULL,
	`resource_type` VARCHAR(255) NULL DEFAULT NULL,
	`resource_id` VARCHAR(255) NULL DEFAULT NULL,
	`ip_address` VARCHAR(255) NULL DEFAULT NULL,
	`action` VARCHAR(255) NULL DEFAULT NULL,
	`time` INT(11) NULL DEFAULT NULL,
	`guest_public_id` VARCHAR(255) NULL DEFAULT NULL,
	INDEX `id` (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
